language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
  - name: "Test with highest versions of Composer dependendcies"
    env: COMPOSER_PARAMS=""
  - name: "Test with highest versions of Composer dependendcies"
    env: COMPOSER_PARAMS="--prefer-lowest"

install:
  - composer update $COMPOSER_PARAMS --no-interaction

script:
  - vendor/bin/phing

cache:
  directories:
    - $HOME/.composer/cache
    - tmp
