language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - master

env:
  matrix:
    - dependencies=lowest
    - dependencies=highest

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction; fi
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi

script:
  - vendor/bin/phing

cache:
  directories:
    - $HOME/.composer/cache
    - tmp
