language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
  - name: "Test with highest versions of Composer dependendcies"
    env: COMPOSER_PARAMS=""
  - name: "Test with highest versions of Composer dependendcies"
    env: COMPOSER_PARAMS="--prefer-lowest"
  - name: "Test usage 1"
    install: 
      - mkdir usage-test && cd usage-test && composer init --repository="name\"path\",url:\"..\""
      - composer require petr-heinz/yaml-tools@dev --no-interaction
    script:
      - usage-test/vendor/bin/yaml-tools fix example.yml
  - name: "Test usage 2"
    install: 
      - mkdir usage-test && cd usage-test && composer init --repository="../composer.json"
      - composer require petr-heinz/yaml-tools@dev --no-interaction
    script:
      - usage-test/vendor/bin/yaml-tools fix example.yml
  - name: "Test usage 3"
    install: 
      - mkdir usage-test && cd usage-test && composer init --repository="name:\"vcs\",url:\"../.git\""
      - composer require petr-heinz/yaml-tools@dev --no-interaction
    script:
      - usage-test/vendor/bin/yaml-tools fix example.yml

install:
  - composer update $COMPOSER_PARAMS --no-interaction

script:
  - vendor/bin/phing

cache:
  directories:
    - $HOME/.composer/cache
    - tmp
