language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
  - name: "Test with highest versions of Composer dependendcies"
    env: COMPOSER_PARAMS=""
  - name: "Test with highest versions of Composer dependendcies"
    env: COMPOSER_PARAMS="--prefer-lowest"
  - name: "Test usage"
    install: 
      - mkdir usage-test && cd usage-test && composer init petr-heinz/yaml-tools-usage-test
      - composer require petr-heinz/yaml-tools@dev --no-interaction
    script:
      - usage-test/vendor/bin/yaml-tools fix example.yml

install:
  - composer update $COMPOSER_PARAMS --no-interaction

script:
  - vendor/bin/phing

cache:
  directories:
    - $HOME/.composer/cache
    - tmp
